export const SET_CONTENT = 'SET_CONTENT';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER ';
export const VisibilityFilters = {
  SHOW_EDITOR: "SHOW_EDITOR",
  SHOW_DOCUMENT: "SHOW_DOCUMENT"
};
